apiVersion: apps/v1
kind: Deployment

metadata:
  name: shoprupee
  namespace: shoprupee

spec:
  replicas: 4

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  selector:
    matchLabels:
      app: shoprupee

  template:
    metadata:
      labels:
        app: shoprupee

    spec:

      imagePullSecrets:
        - name: ecr-registry-secret

        nodeSelector:
  dedicated: nginx

tolerations:
  - key: dedicated
    operator: Equal
    value: nginx
    effect: NoSchedule

      containers:

        - name: shoprupee

          image: SHOPRUPEE_ECR_IMAGE

          imagePullPolicy: Always

          ports:
            - containerPort: 80
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /nginx-health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: 50m
              memory: 64Mi

            limits:
              cpu: 250m
              memory: 128Mi

